name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Client EXE with build_exe.py
        run: |
          python build_exe.py client/client.py  # Build client executable

      - name: Build Server EXE with build_exe.py
        run: |
          python build_exe.py server/server.py  # Build server executable

      - name: Upload Client EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCast-Client
          path: dist/client.exe  # Path to client EXE

      - name: Upload Server EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCast-Server
          path: dist/server.exe  # Path to server EXE
