name: Build EXE and Package with Inno Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build Client EXE with PyInstaller
      - name: Build Client EXE with build_exe.py
        run: |
          python build_exe.py client/client.py  # Build client executable

      # Step 5: Build Server EXE with PyInstaller
      - name: Build Server EXE with build_exe.py
        run: |
          python build_exe.py server/server.py  # Build server executable

      # Step 6: Install Inno Setup using Chocolatey
      - name: Install Inno Setup
        run: |
          choco install innosetup -y  # Install Inno Setup using Chocolatey

      # Step 7: Set Inno Setup executable path dynamically
      - name: Set Inno Setup executable path
        run: |
          # Dynamically find the installation path of Inno Setup
          $InnoSetupPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          echo "Inno Setup installed at: $InnoSetupPath"
          echo "INNO_SETUP_PATH=$InnoSetupPath" >> $GITHUB_ENV  # Store path as environment variable

      # Step 8: Create Installer with Inno Setup
      - name: Create Inno Setup Installer
        run: |
          $INNO_SETUP_PATH = $Env:INNO_SETUP_PATH
          & $INNO_SETUP_PATH installer.iss  # Use the Inno Setup executable from the dynamic path

      # Step 9: Upload Client EXE as Artifact
      - name: Upload Client EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCast-Client
          path: dist/client.exe  # Path to client EXE

      # Step 10: Upload Server EXE as Artifact
      - name: Upload Server EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCast-Server
          path: dist/server.exe  # Path to server EXE

      # Step 11: Upload Installer as Artifact
      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCast-Installer
          path: Output/AudioCast_Installer.exe  # Path to the generated installer
